FROM debian:trixie

ARG USERUID
ARG USERGID

ENV USERID=$USERUID \
    GROUPID=$USERGID

RUN apt-get update && \
apt-get install -y time git subversion build-essential clang ccache ecj fastjar file screen quilt mold ninja-build \
    g++ java-propose-classpath libelf-dev bash make patch libncurses5-dev zlib1g-dev gawk sshpass mtd-utils pbzip2 xxd \
    flex gettext wget unzip xz-utils rsync libncurses-dev libssl-dev tmux binutils-gold help2man liblzma-dev pigz u-boot-tools \
    python3-setuptools python3-dev swig xsltproc nano curl gcc-multilib bison bc libbsd-dev meson pkg-config zstd && \
    apt-get install -y gcc-aarch64-linux-gnu gcc-arm* device-tree-compiler qemu-user-static python-is-python3 texinfo && \
    apt-get clean && \
    groupadd --gid $GROUPID buser && \
    useradd --uid $USERID --gid $GROUPID -m -s /bin/bash buser

# MTK Uartboot recovery tool
COPY mtk_uartboot-v0.1.1/mtk_uartboot /usr/bin/

USER buser
WORKDIR /home/buser

# set dummy git config and quilt settings
RUN git config --global user.name "buser" && git config --global user.email "buser@build-openwrt.com"
COPY quiltrc /home/buser/.quiltrc

# Switch to openwrt folder
WORKDIR /home/buser/openwrt

ENTRYPOINT [ "./build.sh" ]
